[package]
name = "session_types"
version = "0.1.1"
authors = [ "Philip Munksgaard <pmunksgaard@gmail.com>"
          , "Thomas Bracht Laumann Jespersen <laumann.thomas@gmail.com>"
          ]

description = "An implementation of session types in Rust"
repository = "https://github.com/Munksgaard/session-types"
readme = "README.md"
keywords = ["session", "types", "channels", "concurrency", "communication"]

license = "MIT"

[dev-dependencies]
rand = "*"
rand_macros = "*"
compiletest_rs = "*"
