[package]
name = "session_types"
version = "0.2.0"
authors = [ "Philip Munksgaard <pmunksgaard@gmail.com>"
          , "Thomas Bracht Laumann Jespersen <laumann.thomas@gmail.com>"
          ]

description = "An implementation of session types in Rust"
repository = "https://github.com/Munksgaard/session-types"
readme = "README.md"
keywords = ["session", "types", "channels", "concurrency", "communication"]

license = "MIT"

[dev-dependencies]
rand = "0.3.14"

[features]
default = []
chan_select = ["compiletest_rs"]

[dependencies.ipc-channel]
#path = "/home/tj/rust/ipc-channel"
git = "http://github.com/servo/ipc-channel"

[dependencies]
compiletest_rs = { version = "*", optional = true }
serde = "0.6.6"